### ISSUE TITLE
npm install react-native-weibo的时候出现这个错误。

### ISSUE THREAD

**Issue by dongweb** [reactnativecn/react-native-weibo#15]
├── UNMET PEER DEPENDENCY react-native@0.35.0
└─┬ react-native-weibo@3.0.1
  └─┬ es6-promisify@3.0.0
    └── es6-promise@3.3.1

npm WARN react-native-wx@3.0.2 requires a peer of react-native@^0.33.0 but none was installed.

版本必须是从0.33.0这个开始吗？https://github.com/reactnativecn/react-native-wx       这个安装时候也是一样的。

**Comment by sunnylqm** [comment]
是的
