### ISSUE TITLE
无法调用微博的app

### ISSUE THREAD

**Issue by magicwing** [reactnativecn/react-native-weibo#17]
android api 23    rn0.37版本    react-native-weibo最新版本      在模拟器上个没有安装微博app可以正常调用分享功能，   安装微博app后，    调用分享没有任何效果，    原本的分享界面不出来，   微博app也调用不出来，  报错日志没有任何相关信息。

**Comment by tangjihong111** [comment]
解决了吗

**Comment by magicwing** [comment]
解决了，与这项目没有关系，是其他三方项目的问题。 @tangjihong111

**Comment by tangjihong111** [comment]
thanks 。。。。
