### ISSUE TITLE
第三方授权时提示这个错误。

### ISSUE THREAD

**Issue by dongweb** [reactnativecn/react-native-weibo#18]
提示你所访问的站点在微博认证失败，请你联系开发小助手 或者稍后再试（error:invalid_client）。
.请问这个是什么原因？

**Comment by dongweb** [comment]
没有人帮助一下吗？只调用WeiboAPI.login()这个方法不可以吗？这样如果没有安装微博客户端应该是出来微博sso的授权的页面的啊？但是这个页面提示上述描述的错误。网上查到的问题可能的错误是：
第一你的应用在新浪上没有通过审核。
第二通过审核了没有正确把信息填写到ShareSDK.xml配置文件
第三应用打包运行后的签名跟注册时填写的不一样。

已经确定第一条和第三条是没有问题的，第二条不知道react-native-weibo这个该如何操作。

最后还是希望能有大神帮助一下啊？

**Comment by TrustTheBoy** [comment]
@dongweb 请问你怎么解决的？
