### ISSUE TITLE
react-native 0.33  iOS运行失败

### ISSUE THREAD

**Issue by lee11qian** [reactnativecn/react-native-weibo#9]
在RCTWeiboAPI.m中使用了以下方法：
[_bridge.imageLoader loadImageWithTag:imageUrl size:size scale:1 resizeMode:UIViewContentModeScaleToFill progressBlock:nil completionBlock:^(NSError *error, UIImage *image) {
            [self _shareWithData:aData image:image];
        }];
报错：No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithTag:size:scale:...'
对比了一下RN0.33和以前版本的RCTImageLoader.h文件，发现0.33中没有loadImageWithTag方法了。

**Comment by DBshaoYan** [comment]
[_bridge.imageLoader loadImageWithURLRequest:imageUrl size:size scale:1 clipped:FALSE resizeMode:UIViewContentModeScaleToFill progressBlock:nil completionBlock:^(NSError *error, UIImage *image){
            dispatch_async(dispatch_get_main_queue(), ^{
                [self _shareToQQWithData:aData image:image scene:aScene resolve:resolve reject:reject];
            });
        }];
参照这个修改

**Comment by flavordaaave** [comment]
Hmm, this is still not working for me...

<img width="880" alt="bildschirmfoto 2016-11-08 um 19 37 00" src="https://cloud.githubusercontent.com/assets/5305150/20114028/c4000dc4-a5ea-11e6-8d57-00973f67cbd7.png">

**Comment by kingctan** [comment]
i meet the same problem. .........
